controlMoving.o: $(SRC)run/controlMoving.cpp
	$(CXXC) $(COMPFL) $(SRC)run/controlMoving.cpp -o $(BIN)controlMoving.o $(INC)

fillArrays.o: $(SRC)run/fillArrays.cpp
	$(CXXC) $(COMPFL) $(SRC)run/fillArrays.cpp -o $(BIN)fillarrays.o $(INC)

isOutOfBounds.o: $(SRC)run/isOutOfBounds.cpp
	$(CXXC) $(COMPFL) $(SRC)run/isOutOfBounds.cpp -o $(BIN)isOutOfBounds.o $(INC)
