func: controlMoving.o fillArrays.o isOutOfBounds.o

controlMoving.o:./src/run/controlMoving.cpp
	$(CXXC) $(COMPFL) ./src/run/controlMoving.cpp -o $(BIN)run/controlMoving.o $(INC)

fillArrays.o: ./src/run/fillArrays.cpp
	$(CXXC) $(COMPFL) ./src/run/fillArrays.cpp -o $(BIN)run/fillarrays.o $(INC)

isOutOfBounds.o: ./src/run/isOutOfBounds.cpp
	$(CXXC) $(COMPFL) ./src/run/isOutOfBounds.cpp -o $(BIN)run/isOutOfBounds.o $(INC)
